export const products = [
  {
    title: "Tea Tree & Turmeric Bar Soap",
    price: 12000,
    promoPrice: 8400,
    description: "For hyperpigmentation, problematic skin",
    size: "",
    image: "/images/10.webp",
  },
  {
    title: "Aloe & Lavender Soothing Toner",
    price: 15500,
    promoPrice: 10850,
    description: "Balance the skin PH, leaving it refreshed & radiant",
    size: "150ml",
    image: "/images/3.jpeg",
  },
  {
    title: "Treatment Beards wash",
    price: 16500,
    promoPrice: 11500,
    description: "Softens , Condition , & Promotes beards growth",
    size: "500ml",
    image: "/images/4.jpeg",
  },
  {
    title: "NEW Nourish & Flourish collection ",
    price: 75000,
    promoPrice: 52500,
    description: "A bundle that includes all of the head-to-toe essentials to build and maintain healthy and hydrated skin",
    size: "1l",
    image: "/images/5.jpeg",
  },
  {
    title: "Oatmeal Honey Bar Soap",
    price: 12000,
    promoPrice: 8400,
    description: "For dry, sensitive, irritated, itchy skin",
    size: "",
    image: "/images/11.webp",
  },
  {
    title: "Beards Renewal & Restoration oil",
    price: 15000,
    promoPrice: 10500,
    description: "Restores beards shine , Strengthen beards & Treats Ingrown hairs.",
    size: "50ml",
    image: "/images/7.jpeg",
  },
  {
    title: "Beards collection",
    price: 32000,
    promoPrice: 28000,
    description: "Premium kit for a healthier  and fuller beards",
    size: "1l",
    image: "/images/9.jpeg",
  },
  {
    title: "Activated Charcoal Bar Soap",
    price: 12000,
    promoPrice: 8400,
    description: "For oily, acne, combination skin",
    size: "",
    image: "/images/12.webp",
  },
  {
    title: "Neem & Chlorella Bar Soap",
    price: 12000,
    promoPrice: 8400,
    description: "For acne, eczema, psoriasis, oily skin",
    size: "",
    image: "/images/13.webp",
  },
  {
    title: "Chamomile & Calendula Bar Soap",
    price: 12000,
    promoPrice: 8400,
    description: "for eczema, psoriasis, sensitive skin",
    size: "",
    image: "/images/14.webp",
  },
  {
    title: "Coconut & Kaolin Clay Bar Soap",
    price: 12000,
    promoPrice: 8400,
    description: "for sensitive, oily, normal skin",
    size: "",
    image: "/images/15.webp",
  },
  {
    title: "Rosemary & Lavender Bar Soap",
    price: 12000,
    promoPrice: 8400,
    description: "for sensitive, normal skin",
    size: "",
    image: "/images/16.webp",
  },
  {
    title: "Rosewater Kefir & Lavender Bar Soap",
    price: 12000,
    promoPrice: 8400,
    description: "for normal, all skin types, yoni",
    size: "",
    image: "/images/17.webp",
  },
];

// export const
