export const products = [
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/2.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/3.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/4.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/5.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/6.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/7.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/8.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/2.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/2.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/2.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/2.jpeg",
  },
  {
    title: "Classic Transforming Body Lotion",
    price: 200000,
    description: "Oil, hand wash",
    size: "1l",
    image: "/images/2.jpeg",
  },
];
